// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dugdrszapzebhzgjtyef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Z2Ryc3phcHplYmh6Z2p0eWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDczNjMsImV4cCI6MjA2NDAyMzM2M30.SvfoyJdKiT7fP8O_S4t_pSt9eiqxg_PUVk_Wvm4NsLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);